version: '3.8'

services:

  ifn:
    container_name: ifn
    image: node:21.7.1-alpine3.18
    volumes:
      - ./app:/app
      - node-cache:/usr/local/share/.cache
    working_dir: /app
    ports:
      - "3333:3000"
    environment:
      - WDS_SOCKET_PORT=0

volumes:
  node-cache:
