version: '3.8'

services:

  itsfront:
    container_name: itsfront
    image: node:21.7.1-alpine3.18
    volumes:
      - ./front:/app
      - node-cache:/usr/local/share/.cache
    working_dir: /app
    ports:
      - "3333:3000"
    environment:
      - WDS_SOCKET_PORT=0
    command: "npm start"

  itsback:
    container_name: itsback
    image: node:21.7.1-alpine3.18
    volumes:
      - ./back:/app
      - node-cache:/usr/local/share/.cache
    working_dir: /app
    ports:
      - "3000:3000"
    command: "npm run start:dev"

  itsdata:
    container_name: itsdata
    build:
      context: data
    volumes:
      - ./data:/app
    working_dir: /app
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    command: "python -m flask --app app run --debug -p 8000 -h 0.0.0.0"

volumes:
  node-cache:
